######################################################
# Fichier de test des routes HTTP de l'API
#######################################################

@endpoint = http://localhost:3000/

#########################
#      User       #
#########################

### liste des users
GET {{ endpoint }}user

## Récupérér un user par son id
GET {{ endpoint }}user/1

#########################
#      CLient       #
#########################

### liste des users
GET {{ endpoint }}client

## Récupérér un user par son id
GET {{ endpoint }}user/1