######################################################
# Fichier de test des routes HTTP de l'API
#######################################################

@endpoint = http://localhost:3000/

#########################
#      User       #
#########################

### liste des users
GET {{ endpoint }}user

## Récupérér un user par son id
GET {{ endpoint }}user/2

### Créer un user en JSON
POST {{ endpoint }}user
content-type: application/json
{
    "mail": "user3@gmail.co",
    "password": "SecurePassword456!",
		"siret": "Null",
		"siren": "Null",
		"name": "Petite Fleur",
		"adress": "752 Prout St",
	  "zip_code": "45644",
	  "city": "city3",
	  "number": "0658634159"
}

#########################
#      CLient       #
#########################

### liste des users
GET {{ endpoint }}client

## Récupérér un user par son id
GET {{ endpoint }}user/1