######################################################
# Fichier de test des routes HTTP de l'API
#######################################################

@endpoint = http://localhost:{{$dotenv PORT}}

#########################
#      User       #
#########################

### liste des users
GET {{ endpoint }}/user